name: awsgoo
services:

  sc-eureka:
    image: rudals831/project-eureka:0.1.0
    container_name: sc-eureka
    ports:
      - "8765:8761"                 # 호스트 8765 → 컨테이너 8761
    environment:
      - SERVER_PORT=8761
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info
      - MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED=true
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost:8761/actuator/health | grep -q UP || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 30
    networks: [msa-net]

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root_pass_123!
      MARIADB_DATABASE: project_user
      MARIADB_USER: appuser
      MARIADB_PASSWORD: app_pass_123!
    healthcheck:
      test: ["CMD-SHELL","mariadb-admin ping -h 127.0.0.1 -u${MARIADB_USER} -p${MARIADB_PASSWORD} --silent"]
      interval: 10s
      timeout: 3s
      retries: 30
    volumes:
      - mariadb_data:/var/lib/mysql
    networks: [msa-net]

  sc-user-svc:
    image: rudals831/project-user:0.1.4
    environment:
      - SERVER_PORT=8081
      - SPRING_APPLICATION_NAME=project-user
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://sc-eureka:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/project_user
      - SPRING_DATASOURCE_USERNAME=appuser
      - SPRING_DATASOURCE_PASSWORD=app_pass_123!
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MariaDBDialect
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info
      - MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED=true
    depends_on:
      sc-eureka: { condition: service_healthy }
      mariadb:   { condition: service_healthy }
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost:8081/actuator/health | grep -q UP || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 30
    networks: [msa-net]

  scg-proxy:
    image: rudals831/project-scg:0.1.3
    environment:
      - SERVER_PORT=8080
      - SPRING_APPLICATION_NAME=sc-gateway
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://sc-eureka:8761/eureka
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED=true
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID=true
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info
      - MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED=true
    depends_on:
      sc-eureka:   { condition: service_healthy }
      sc-user-svc: { condition: service_healthy }
    ports:
      - "9080:8080"
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost:8080/actuator/health | grep -q UP || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 30
    networks: [msa-net]

networks:
  msa-net:
    driver: bridge

volumes:
  mariadb_data:
